spring:
  application:
    name: employee-api

server:
  port: 8111
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024
  http2:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,openapi,swagger-ui
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true

info:
  app:
    name: ${spring.application.name}
    description: Employee Management API
    version: 1.0.0
    java:
      version: ${java.version}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

resilience4j:
  circuitbreaker:
    instances:
      employee-service:
        sliding-window-size: 20
        failure-rate-threshold: 60
        wait-duration-in-open-state: 60s
        slow-call-rate-threshold: 60
        slow-call-duration-threshold: 3s
        permitted-number-of-calls-in-half-open-state: 5
        automatic-transition-from-open-to-half-open-enabled: true
        event-consumer-buffer-size: 10
        register-health-indicator: true
        record-exceptions:
          - org.springframework.web.client.HttpServerErrorException
          - org.springframework.web.client.HttpClientErrorException$TooManyRequests
          - org.springframework.web.client.ResourceAccessException
          - java.net.SocketTimeoutException
          - java.util.concurrent.TimeoutException
        ignore-exceptions:
          - com.reliaquest.api.exception.EmployeeNotFoundException
  ratelimiter:
    instances:
      employee-service:
        limit-for-period: 10
        limit-refresh-period: 1s
        timeout-duration: 2s
        register-health-indicator: true
  retry:
    instances:
      employee-service:
        max-attempts: 3
        wait-duration: 1s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        exponential-max-wait-duration: 10s
        retry-exceptions:
          - org.springframework.web.client.HttpServerErrorException
          - org.springframework.web.client.HttpClientErrorException$TooManyRequests
          - org.springframework.web.client.ResourceAccessException
          - java.net.SocketTimeoutException
          - java.util.concurrent.TimeoutException
        ignore-exceptions:
          - com.reliaquest.api.exception.EmployeeNotFoundException

employee:
  api:
    base-url: http://localhost:8112/api/v1/employee